# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb-auth-slice-password-reset}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman", "Christian Kebekus"]
  s.date = %q{2010-04-22}
  s.description = %q{Merb Slice for password-reset functionality}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "app/controllers/application.rb",
     "app/controllers/passwords.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/mailer_helper.rb",
     "app/mailers/password_reset_mailer.rb",
     "app/mailers/views/password_reset_mailer/new_password.html.erb",
     "app/mailers/views/password_reset_mailer/password_reset.text.erb",
     "app/views/layout/merb_auth_slice_password_reset.html.erb",
     "app/views/passwords/forgot_password.html.erb",
     "config/init.rb",
     "lib/merb-auth-slice-password-reset.rb",
     "lib/merb-auth-slice-password-reset/merbtasks.rb",
     "lib/merb-auth-slice-password-reset/mixins/senile_user.rb",
     "lib/merb-auth-slice-password-reset/mixins/senile_user/ar_senile_user.rb",
     "lib/merb-auth-slice-password-reset/mixins/senile_user/dm_senile_user.rb",
     "lib/merb-auth-slice-password-reset/mixins/senile_user/sq_senile_user.rb",
     "lib/merb-auth-slice-password-reset/slicetasks.rb",
     "lib/merb-auth-slice-password-reset/spectasks.rb",
     "merb-auth-slice-password-reset.gemspec",
     "public/javascripts/master.js",
     "public/stylesheets/master.css",
     "spec/mailers/password_reset_mailer_spec.rb",
     "spec/mixins/senile_user_spec.rb",
     "spec/spec_helper.rb",
     "stubs/app/controllers/passwords.rb",
     "stubs/app/mailers/views/password_reset_mailer/new_password.html.erb",
     "stubs/app/mailers/views/password_reset_mailer/password_reset.text.erb",
     "stubs/app/views/passwords/forgot_password.html.erb"
  ]
  s.homepage = %q{http://merbivore.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Merb Slice that adds basic password-reset functionality to merb-auth-based merb applications.}
  s.test_files = [
    "spec/mailers/password_reset_mailer_spec.rb",
     "spec/mixins/senile_user_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-slices>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<merb-auth-core>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<merb-auth-more>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<merb-mailer>, ["~> 1.1.0"])
    else
      s.add_dependency(%q<merb-slices>, ["~> 1.1.0"])
      s.add_dependency(%q<merb-auth-core>, ["~> 1.1.0"])
      s.add_dependency(%q<merb-auth-more>, ["~> 1.1.0"])
      s.add_dependency(%q<merb-mailer>, ["~> 1.1.0"])
    end
  else
    s.add_dependency(%q<merb-slices>, ["~> 1.1.0"])
    s.add_dependency(%q<merb-auth-core>, ["~> 1.1.0"])
    s.add_dependency(%q<merb-auth-more>, ["~> 1.1.0"])
    s.add_dependency(%q<merb-mailer>, ["~> 1.1.0"])
  end
end

